### ISSUE TITLE
Launching DevDocs installed HTML5 app and not opening the browser itself

### ISSUE THREAD

**Issue by StephanBeer** [deibit/vscode-devdocs#5]
Hello and thanks for making the DevDocs extension for VSCode. Any chance for a workarround or update to make the extension launch devdocs not by starting the browser and opening a new tab, rather then launching the downloaded offline chrome (google and also edge chromium)app, maybe even IN Visual Studio Code ?

The downloaded offline version of DevDocs (HTML5 app) is working fine, but everytime when searching you have to go outside VSCode and switch Apps.

**Comment by deibit** [comment]
Hello Stephan. 

It is a interesting feature but...

From a comment in [an alternative](https://marketplace.visualstudio.com/items?itemName=akfish.vscode-devdocs) devdocs extension for VSCode:

> WARNING: Due to restriction imposed by vscode.previewHtml, all preferences and offline data for DevDocs will be lost after VSCode restart. It is not recommended to use this extension any more.

The solution could be in an external viewer (Desktop app or local server) with all interesting devdocs pages cached there and a handler to open links from VSCode. Very outside of our scope: just a simple extension.

Thank you.
